import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      // Use the existing public/manifest.json
      manifest: false,
      includeAssets: ['RentDesk.png', 'Unitra*.png'],
      workbox: {
        // Cache all JS/CSS/HTML assets generated by Vite
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
        // Network-first for API/Firebase calls, cache-first for static assets
        runtimeCaching: [
          {
            // Firebase Auth / Firestore / Storage
            urlPattern: /^https:\/\/(firestore|identitytoolkit|securetoken|firebasestorage)\.googleapis\.com\//,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'firebase-cache',
              expiration: { maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 },
            },
          },
          {
            // Google Fonts (if any)
            urlPattern: /^https:\/\/fonts\.(googleapis|gstatic)\.com\//,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts',
              expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 },
            },
          },
        ],
      },
      devOptions: {
        // Enable SW in dev mode for testing (disable if it causes issues)
        enabled: false,
      },
    }),
  ],
  server: {
    port: 3000,
    strictPort: true,
    host: '0.0.0.0',
  },
})
