import type { Course } from '../types';

export const adminCourse: Course = {
  id: 'course-admin-fundamentals',
  title: 'System Administrator Fundamentals',
  description: 'A complete guide to setting up and managing RentDesk as a System Administrator. Covers facilities, rooms, users, leases, payments, reports, and more.',
  track: 'system_admin',
  estimatedHours: 3,
  certificateTitle: 'Certified RentDesk System Administrator',
  modules: [
    // ──────────────────────────────────────────────────────────────────────────
    {
      id: 'mod-system-setup',
      title: 'System Setup & Organization',
      description: 'Set up your organization, create facilities, add rooms, and understand the core data structure.',
      icon: 'Building2',
      lessons: [
        {
          id: 'lesson-system-overview',
          title: 'Understanding RentDesk',
          estimatedMinutes: 5,
          objective: 'Understand how RentDesk is structured and what a System Administrator is responsible for.',
          blocks: [
            { type: 'paragraph', content: 'Welcome to RentDesk — your complete rental management system. Before diving in, it helps to understand how everything fits together.' },
            { type: 'heading', content: 'The Core Structure' },
            { type: 'paragraph', content: 'RentDesk is built around a simple hierarchy. Everything starts with a **Facility** (a property or building), which contains **Rooms**. Each room can be rented to a **Renter** through a **Lease**, and every lease generates a **Payment Schedule**.' },
            { type: 'key_term', term: 'Facility', content: 'A physical property or building you manage. One organization can have multiple facilities.' },
            { type: 'key_term', term: 'Room', content: 'An individual rentable unit within a facility. Has a status: available, occupied, locked, empty, maintenance, or unavailable.' },
            { type: 'key_term', term: 'Renter', content: 'A person who rents a room. Stores personal info, documents, and emergency contacts.' },
            { type: 'key_term', term: 'Lease', content: 'The agreement between a renter and a room. Defines rent, deposit, dates, and terms.' },
            { type: 'key_term', term: 'Payment Schedule', content: 'Auto-generated from the lease. One entry per month showing what is owed and what has been paid.' },
            { type: 'heading', content: 'Your Role as System Administrator' },
            { type: 'paragraph', content: 'As a System Administrator you have full access to everything in RentDesk. You are responsible for:' },
            { type: 'checklist', items: ['Setting up facilities and rooms', 'Inviting and managing staff users', 'Configuring organization-wide settings (late fees, auto-lock, permissions)', 'Approving payment changes made by standard users', 'Running reports and monitoring the health of the business', 'Handling lease terminations and deposit payouts'] },
            { type: 'tip', content: '**Standard Users** (your staff) can do most day-to-day tasks, but they need you to approve certain payment changes. This keeps the audit trail clean and prevents errors.' },
          ],
        },
        {
          id: 'lesson-create-facility',
          title: 'Creating Your First Facility',
          estimatedMinutes: 7,
          objective: 'Create a facility with correct business rules so rooms and leases behave as expected.',
          blocks: [
            { type: 'paragraph', content: 'A facility is the foundation of everything. You must create at least one facility before you can add rooms or manage tenants.' },
            { type: 'heading', content: 'Step-by-Step: Create a Facility' },
            { type: 'numbered_steps', items: [
              'Click **Facilities** in the left sidebar.',
              'Click the **"+ Add Facility"** button in the top right.',
              'Enter the facility **Name** — this is how it will appear throughout the system.',
              'Enter the full **Address** of the property.',
              'Add **Contact Info**: a phone number and email for this facility.',
              'Enter the **Billing Entity** name (the legal name used on invoices, if different from the facility name).',
              'Set the **Business Rules** (see below) — these are the defaults for all rooms in this facility.',
              'Click **Save**.',
            ]},
            { type: 'heading', content: 'Business Rules Explained' },
            { type: 'key_term', term: 'Late Fee Amount', content: 'The rand amount added to a payment when it is overdue. Example: R20.' },
            { type: 'key_term', term: 'Late Fee Start Day', content: 'The day of the month after which a payment is considered late. Example: 4 means any payment not received by the 4th is subject to the late fee.' },
            { type: 'key_term', term: 'Grace Period Days', content: 'Additional days after the late fee start day before escalation actions are taken.' },
            { type: 'key_term', term: 'Child Surcharge', content: 'An additional monthly amount charged per child in the room. Example: R10 per child.' },
            { type: 'key_term', term: 'Payment Methods', content: 'Which payment methods are accepted at this facility (cash, EFT, mobile, card).' },
            { type: 'warning', content: 'If you change the late fee amount after leases are already active, it will only affect **new** payment entries going forward. Existing overdue entries keep their original late fee.' },
            { type: 'tip', content: 'You can have multiple facilities with different business rules. A budget property might have a lower late fee, while a premium property might have stricter rules.' },
          ],
        },
        {
          id: 'lesson-add-room',
          title: 'Adding Rooms to a Facility',
          estimatedMinutes: 8,
          objective: 'Add rooms with the correct type, pricing, and status so they are ready for tenants.',
          blocks: [
            { type: 'paragraph', content: 'Rooms are the core unit of your rental business. Each room has its own status, pricing, and history. You must add rooms before you can create leases.' },
            { type: 'heading', content: 'Step-by-Step: Add a Room' },
            { type: 'numbered_steps', items: [
              'Click **Rooms** in the sidebar.',
              'Select the facility you want to add rooms to from the facility dropdown at the top.',
              'Click **"+ Add Room"**.',
              'Enter the **Room Number** (e.g. "101", "A2", "Ground Floor Unit"). This is the identifier used everywhere in the system.',
              'Choose the **Room Type**: Single, Double, Family, or Studio.',
              'Set the **Monthly Rent** amount in rands.',
              'Set the **Deposit Amount** (typically equal to one month\'s rent).',
              'Set the **Capacity** (maximum number of occupants).',
              'Add any **Amenities** that apply (e.g. en-suite, balcony, parking).',
              'Click **Save**.',
            ]},
            { type: 'heading', content: 'Room Types Explained' },
            { type: 'checklist', items: ['**Single** — one occupant, one bed', '**Double** — couple or two occupants, double or two beds', '**Family** — multiple occupants including children', '**Studio** — open-plan unit with combined living/sleeping space'] },
            { type: 'heading', content: 'Initial Room Status' },
            { type: 'paragraph', content: 'When you create a room, its status is set to **Available** — meaning it is ready to be rented. Once a lease is created for the room, the status automatically changes to **Occupied**.' },
            { type: 'tip', content: 'If a room needs renovation before it can be rented, set its status to **Maintenance** after creating it. This prevents it from appearing as available to standard users.' },
            { type: 'warning', content: 'Only System Administrators can change the **Monthly Rent** and **Deposit Amount** on a room. Standard users can see these values but cannot edit them — this prevents unauthorized price changes.' },
          ],
        },
        {
          id: 'lesson-room-statuses',
          title: 'Room Status Lifecycle',
          estimatedMinutes: 8,
          objective: 'Understand all room statuses, when they change, and what each one means operationally.',
          blocks: [
            { type: 'paragraph', content: 'Room status is one of the most important concepts in RentDesk. It drives what actions are available, what auto-lock rules apply, and what appears on reports.' },
            { type: 'heading', content: 'All Six Room Statuses' },
            { type: 'key_term', term: 'Available', content: 'The room is empty and ready to rent. No active lease. Appears on occupancy reports as vacant.' },
            { type: 'key_term', term: 'Occupied', content: 'A tenant is living in the room and paying rent normally. Active lease exists.' },
            { type: 'key_term', term: 'Locked', content: 'The tenant is behind on rent. The key has been withheld. The room is still occupied but access is restricted. Once payment is received, it auto-reverts to Occupied.' },
            { type: 'key_term', term: 'Empty', content: 'The room was occupied but the tenant has vacated without formal termination, OR it is a new room that needs a deposit before the first month\'s rent. Deposit must be collected before regular rent.' },
            { type: 'key_term', term: 'Maintenance', content: 'The room is undergoing repairs or cleaning. Not available for new leases. Use this during renovation periods.' },
            { type: 'key_term', term: 'Unavailable', content: 'The room is taken off the market permanently or for an extended period. Similar to maintenance but implies no near-term return to service.' },
            { type: 'heading', content: 'Automatic Status Changes' },
            { type: 'checklist', items: [
              '**Available → Occupied**: happens automatically when you create a lease for the room',
              '**Occupied → Locked**: happens automatically when the auto-lock check runs (on login or daily schedule) and the current month\'s rent is still unpaid past the threshold',
              '**Locked → Occupied**: happens automatically when the outstanding payment is received and approved',
              '**Occupied → Available**: happens when a lease is terminated (manual)',
            ]},
            { type: 'warning', content: 'Do not manually unlock (set to Occupied) a locked room until you have confirmed payment has been received. Auto-unlock only happens via the payment system.' },
            { type: 'tip', content: 'The **Auto-Lock After Days** setting (in Organization Settings) controls how many days into the month the system waits before locking. Default is 5 — so if rent is still unpaid on the 6th of the month, the room locks.' },
          ],
        },
      ],
    },
    // ──────────────────────────────────────────────────────────────────────────
    {
      id: 'mod-user-management',
      title: 'User Management',
      description: 'Invite staff, configure what they can access, and manage accounts.',
      icon: 'Users',
      lessons: [
        {
          id: 'lesson-user-roles',
          title: 'Understanding User Roles',
          estimatedMinutes: 5,
          objective: 'Know the difference between System Admin and Standard User and when to assign each.',
          blocks: [
            { type: 'paragraph', content: 'RentDesk has two user roles. Understanding the difference helps you assign appropriate access to your staff.' },
            { type: 'heading', content: 'System Administrator' },
            { type: 'paragraph', content: 'Full access to everything. Can create and delete data, configure settings, approve payments, view all reports, manage users, and access all facilities. Typically: the business owner or senior manager.' },
            { type: 'heading', content: 'Standard User' },
            { type: 'paragraph', content: 'Day-to-day operational access. Can capture payments, manage renters and leases, update room statuses, and log complaints. What they can access is configurable by the admin.' },
            { type: 'key_term', term: 'Permission Toggle', content: 'In Organization Settings, you can switch on/off what standard users can see: Facilities, Rooms, Leases, Payments, Renters, Maintenance, Penalties.' },
            { type: 'tip', content: 'Start with the **least access** needed and expand over time. A standard user who only captures payments does not need access to Facilities or Settings.' },
            { type: 'warning', content: 'There is no "read-only" mode for standard users currently. If you give them access to a section, they can modify data in that section.' },
          ],
        },
        {
          id: 'lesson-invite-user',
          title: 'Inviting Staff Users',
          estimatedMinutes: 6,
          objective: 'Successfully invite a new user so they can log in and start working.',
          blocks: [
            { type: 'paragraph', content: 'Users are invited by email. They receive a link to set their own password — you never set passwords on behalf of users.' },
            { type: 'heading', content: 'Step-by-Step: Invite a User' },
            { type: 'numbered_steps', items: [
              'Click **Settings** in the header (gear icon) or navigate to **/settings**.',
              'Go to the **Users** tab.',
              'Click **"Invite User"**.',
              'Enter the staff member\'s **First Name**, **Last Name**, and **Email Address**.',
              'Select their **Role**: System Admin or Standard User.',
              'Click **Send Invitation**.',
              'The system sends an email with a secure link. The link expires in **7 days**.',
              'The user clicks the link, sets their password, and can immediately log in.',
            ]},
            { type: 'heading', content: 'What the Invitation Email Contains' },
            { type: 'checklist', items: ['Welcome message with their name and assigned role', 'A "Set Up Your Password" button (secure one-time link)', 'Expiry notice (7 days)', 'Instructions on what RentDesk is used for'] },
            { type: 'tip', content: 'If the invitation expires before the user sets up their account, you can send a new invitation from the Users tab — just invite again with the same email.' },
            { type: 'warning', content: 'Do not share your own admin login credentials. Always invite users through the proper invitation flow so each person has their own account and actions are tracked individually.' },
          ],
        },
        {
          id: 'lesson-org-settings',
          title: 'Organization-Wide Settings',
          estimatedMinutes: 8,
          objective: 'Configure the core business rules that apply across all facilities.',
          blocks: [
            { type: 'paragraph', content: 'Organization Settings control the global behaviour of RentDesk. Changes here affect all facilities unless overridden at the facility level.' },
            { type: 'heading', content: 'How to Access Settings' },
            { type: 'numbered_steps', items: ['Click the **gear icon** in the top right header, or navigate to **/settings**.', 'Use the tabs at the top to navigate: **Payment**, **Permissions**, **Business Rules**, **Users**.'] },
            { type: 'heading', content: 'Payment Settings' },
            { type: 'key_term', term: 'Payment Due Date', content: 'Set to "First Day of Month" or "Last Day of Month". Controls when payment entries are considered due.' },
            { type: 'key_term', term: 'Allow Standard User Past Payments', content: 'If ON, standard users can capture payments for past months. If OFF, only admins can.' },
            { type: 'key_term', term: 'Require Admin Approval for Past Payments', content: 'If ON, past-date payments captured by standard users go into a "pending approval" state before being recorded.' },
            { type: 'key_term', term: 'Max Past Payment Days', content: 'How many days back a standard user is allowed to record a payment.' },
            { type: 'key_term', term: 'Auto-Lock After Days', content: 'How many days into the month before an unpaid room is automatically locked. Default: 5.' },
            { type: 'heading', content: 'User Permissions' },
            { type: 'paragraph', content: 'Each toggle controls whether standard users can see and use a particular section of the app. Turn off anything your standard users do not need.' },
            { type: 'heading', content: 'Business Rules' },
            { type: 'paragraph', content: 'Default Late Fee and Default Child Surcharge are the fallback values used when a facility does not set its own. Always keep these up to date with your current business policy.' },
            { type: 'warning', content: 'Changes to Business Rules take effect immediately. If you increase the late fee, the next time the system calculates penalties it will use the new value.' },
          ],
        },
      ],
    },
    // ──────────────────────────────────────────────────────────────────────────
    {
      id: 'mod-renter-lease',
      title: 'Renters & Leases',
      description: 'Add renters, create leases, manage the acceptance process, and handle terminations.',
      icon: 'FileText',
      lessons: [
        {
          id: 'lesson-add-renter',
          title: 'Adding a New Renter',
          estimatedMinutes: 7,
          objective: 'Create a complete renter profile with all required information.',
          blocks: [
            { type: 'paragraph', content: 'Before you can create a lease, the renter must exist in the system. A complete renter profile speeds up any future disputes, eviction proceedings, or communication.' },
            { type: 'heading', content: 'Step-by-Step: Add a Renter' },
            { type: 'numbered_steps', items: [
              'Click **Renters** in the sidebar.',
              'Click **"+ Add Renter"**.',
              'Fill in **Personal Information**: First name, Last name, ID Number, Phone, Email.',
              'Fill in the **Emergency Contact**: name, phone, and relationship.',
              'Upload any documents: **ID copy**, proof of income, references (optional but recommended).',
              'Set the **Renter Status** to Active (default).',
              'Click **Save**.',
            ]},
            { type: 'heading', content: 'Required vs Optional Fields' },
            { type: 'checklist', items: [
              '**Required**: First name, Last name, Phone number',
              '**Strongly recommended**: ID number (for legal purposes), Email (for notifications), Emergency contact',
              '**Optional**: Documents (ID copy, proof of income)',
            ]},
            { type: 'tip', content: 'The **ID Number** is critical for South African compliance. Always capture it accurately — it is used in lease documents and legal correspondence.' },
            { type: 'warning', content: 'A renter with status **Blacklisted** cannot have a new lease created. If you accidentally blacklist someone, you must change the status back to Active first.' },
          ],
        },
        {
          id: 'lesson-create-lease',
          title: 'Creating a Lease',
          estimatedMinutes: 10,
          objective: 'Create a lease that correctly links a renter to a room and generates the payment schedule.',
          blocks: [
            { type: 'paragraph', content: 'A lease is the legal and operational core of the rental relationship. When you save a lease, RentDesk automatically creates the payment schedule for the entire lease period.' },
            { type: 'heading', content: 'Pre-requisites' },
            { type: 'checklist', items: ['The renter must already exist in the system', 'The room must exist and have status **Available** or **Empty**', 'You need the agreed rent amount, deposit amount, and start date'] },
            { type: 'heading', content: 'Step-by-Step: Create a Lease' },
            { type: 'numbered_steps', items: [
              'Click **Leases** in the sidebar.',
              'Click **"+ New Lease"**.',
              'Select the **Facility** and then the **Room** (only available/empty rooms will appear).',
              'Search for and select the **Renter** — type their name or ID number to find them.',
              'Set the **Start Date** (move-in date).',
              'For fixed-term leases, set the **End Date**. For monthly rolling leases, leave end date blank.',
              'Set the **Monthly Rent** amount (pre-filled from the room, but can be adjusted).',
              'Set the **Deposit Amount** (pre-filled from the room, but can be adjusted).',
              'Enter the **Number of Children** (0 if none) — this adds the child surcharge to rent.',
              'Select the **Lease Type**: Monthly Rolling or Fixed-Term.',
              'Click **Create Lease**.',
            ]},
            { type: 'heading', content: 'What Happens After Saving' },
            { type: 'checklist', items: [
              'The room status changes from Available → Occupied',
              'A payment schedule is generated with one entry per month',
              'The first entry is typically a **Deposit** payment',
              'Subsequent entries are monthly **Rent** payments',
              'The lease appears in the Leases list with status Active',
            ]},
            { type: 'warning', content: 'If the room was previously **Empty** (tenant moved out without formal termination), the first payment must be a **deposit** before regular rent is accepted. The system enforces this automatically.' },
          ],
        },
        {
          id: 'lesson-lease-accept',
          title: 'Lease Acceptance: Photo & Accept Button',
          estimatedMinutes: 6,
          objective: 'Complete the lease acceptance process using the photo-based confirmation method.',
          blocks: [
            { type: 'paragraph', content: 'RentDesk uses a photo-based acceptance process instead of e-signature. The tenant reviews the lease terms and the staff member takes a photo of the tenant acknowledging agreement.' },
            { type: 'heading', content: 'The Acceptance Process' },
            { type: 'numbered_steps', items: [
              'Open the lease from the **Leases** page.',
              'Click **"View Lease"** to open the lease document.',
              'Review all lease terms with the tenant (rent, deposit, dates, rules).',
              'Once the tenant agrees, click the **"Accept Lease"** button.',
              'You will be prompted to **take or upload a photo** of the tenant — this is the acknowledgement evidence.',
              'The photo is stored securely and the lease status is updated to **Accepted**.',
            ]},
            { type: 'tip', content: 'The acceptance photo should show the tenant\'s face clearly, or ideally the tenant holding a signed paper acknowledgement. This provides legal evidence if disputes arise later.' },
            { type: 'note', content: 'If you are using RentDesk on a mobile device, the camera will open directly. On desktop, you can upload a photo file taken separately.' },
          ],
        },
        {
          id: 'lesson-lease-termination',
          title: 'Terminating a Lease',
          estimatedMinutes: 10,
          objective: 'Correctly terminate a lease, handle outstanding payments, and initiate the deposit payout.',
          blocks: [
            { type: 'paragraph', content: 'Lease termination is a multi-step process. Done correctly, it settles all outstanding amounts and prepares the room for the next tenant.' },
            { type: 'heading', content: 'Step-by-Step: Terminate a Lease' },
            { type: 'numbered_steps', items: [
              'Go to **Leases** and find the active lease you want to terminate.',
              'Click the **terminate icon** (scissors icon) next to the lease.',
              'Set the **Termination Date** — the date the tenant vacates.',
              'Select the **Termination Reason**: end of term, mid-term, breach, mutual agreement, or other.',
              'Add any **Termination Notes** for the record.',
              'The system calculates all **Outstanding Payments** (any unpaid months including prorated final month).',
              'Review and optionally add **Additional Charges** (cleaning, repairs, damage).',
              'Review the **Deposit Refund** calculation — deposit minus deductions minus outstanding.',
              'Click **Process Termination**.',
            ]},
            { type: 'heading', content: 'Post-Inspection Before Termination' },
            { type: 'paragraph', content: 'The termination form includes a **"Start Inspection"** button. You should always conduct a post-inspection before finalizing the termination. The inspection checklist captures the room\'s condition and any repair costs, which are automatically deducted from the deposit refund.' },
            { type: 'warning', content: 'Once a termination is processed, the room status changes to **Available**. You cannot undo this without creating a new lease. Always double-check the deposit refund calculation before clicking Process Termination.' },
            { type: 'heading', content: 'What Happens After Termination' },
            { type: 'checklist', items: [
              'Lease status changes to Terminated',
              'Room status changes to Available (or Maintenance if you set it)',
              'Outstanding payments are recorded',
              'Deposit payout is recorded',
              'The history is preserved for audit purposes',
            ]},
          ],
        },
      ],
    },
    // ──────────────────────────────────────────────────────────────────────────
    {
      id: 'mod-payments-admin',
      title: 'Payment Management',
      description: 'Understand payment schedules, approve changes, handle overdue accounts, and manage deposits.',
      icon: 'CreditCard',
      lessons: [
        {
          id: 'lesson-payment-schedules',
          title: 'Understanding Payment Schedules',
          estimatedMinutes: 6,
          objective: 'Read and interpret a payment schedule so you can quickly assess a tenant\'s financial status.',
          blocks: [
            { type: 'paragraph', content: 'Every active lease has a payment schedule — a month-by-month record of what is owed and what has been paid.' },
            { type: 'heading', content: 'Payment Entry Statuses' },
            { type: 'key_term', term: 'Pending', content: 'Payment is due but has not been received yet. Normal state early in the month.' },
            { type: 'key_term', term: 'Paid', content: 'Full payment received and confirmed.' },
            { type: 'key_term', term: 'Partial', content: 'Some payment received, balance outstanding.' },
            { type: 'key_term', term: 'Overdue', content: 'Past the due date and still unpaid or partially paid. May trigger late fee.' },
            { type: 'key_term', term: 'Pending Approval', content: 'A standard user has captured the payment, but it awaits admin approval before being confirmed.' },
            { type: 'heading', content: 'Viewing a Payment Schedule' },
            { type: 'numbered_steps', items: [
              'Go to **Payments** in the sidebar.',
              'Use the search bar to find the tenant or room.',
              'Click on the payment row to see details.',
              'The schedule shows all months from lease start to present.',
            ]},
            { type: 'tip', content: 'The Payments page has a **"Overdue"** filter at the top. Use this every Monday morning to quickly see who hasn\'t paid.' },
          ],
        },
        {
          id: 'lesson-approve-payments',
          title: 'Approving Payment Changes',
          estimatedMinutes: 7,
          objective: 'Review, approve, or reject payment changes submitted by standard users.',
          blocks: [
            { type: 'paragraph', content: 'When a standard user captures a payment that requires admin approval (e.g. a past-date payment), it enters a **Pending Approval** state. You will receive a notification and can review it from the Payment Approvals page.' },
            { type: 'heading', content: 'Approving a Payment' },
            { type: 'numbered_steps', items: [
              'Click **Payment Approvals** in the sidebar (system admin only).',
              'You will see all payments waiting for your review.',
              'Click on a payment to see the full details: amount, method, date, captured by, notes.',
              'If everything is correct, click **Approve** and optionally add approval notes.',
              'The payment status updates to **Paid** and the capturing user is notified.',
            ]},
            { type: 'heading', content: 'Rejecting a Payment' },
            { type: 'numbered_steps', items: [
              'On the same approval screen, click **Reject**.',
              'You **must** enter a reason for rejection.',
              'The payment is sent back to Pending and the capturing user is notified with your reason.',
            ]},
            { type: 'tip', content: 'Common reasons to reject: wrong amount entered, wrong month selected, payment method mismatch with the receipt provided.' },
            { type: 'warning', content: 'Rejecting does not delete the record — it flags it for correction. The standard user can update and resubmit, or you can capture the corrected payment yourself.' },
          ],
        },
        {
          id: 'lesson-overdue-autolock',
          title: 'Overdue Accounts & Auto-Lock',
          estimatedMinutes: 8,
          objective: 'Understand how RentDesk automatically locks overdue rooms and what to do when this happens.',
          blocks: [
            { type: 'paragraph', content: 'RentDesk has an automatic room-locking system that protects your business by withholding key access from tenants who haven\'t paid.' },
            { type: 'heading', content: 'How Auto-Lock Works' },
            { type: 'numbered_steps', items: [
              'Every day at 8 AM (server time), the system checks all occupied rooms.',
              'If today\'s date is more than **Auto-Lock After Days** past the 1st of the month AND the current month\'s rent is still Pending, the room is locked.',
              'The room status changes from **Occupied → Locked**.',
              'All System Administrators receive a notification: "Room X auto-locked — overdue rent."',
              'On the next login, each admin also sees the lock applied.',
            ]},
            { type: 'heading', content: 'What to Do When a Room Is Locked' },
            { type: 'numbered_steps', items: [
              'Contact the tenant to arrange payment.',
              'Once payment is received, capture it in the Payments section.',
              'If the payment requires approval, approve it from Payment Approvals.',
              'Once the payment is confirmed (approved or directly paid), the room status automatically reverts to **Occupied**.',
              'Admins receive a notification: "Room X auto-unlocked after payment."',
            ]},
            { type: 'warning', content: 'Never manually change a locked room to Occupied without confirming payment has been received. This defeats the purpose of the lock and breaks the payment audit trail.' },
            { type: 'tip', content: 'You can configure how many days the system waits before locking in **Settings → Payment → Auto-Lock After Days**. The default is 5 days — meaning rooms lock on the 6th if unpaid.' },
          ],
        },
      ],
    },
    // ──────────────────────────────────────────────────────────────────────────
    {
      id: 'mod-inspections',
      title: 'Inspections',
      description: 'Conduct pre- and post-tenancy inspections to protect deposit decisions.',
      icon: 'ClipboardCheck',
      lessons: [
        {
          id: 'lesson-inspections-overview',
          title: 'Why Inspections Matter',
          estimatedMinutes: 4,
          objective: 'Understand when to conduct inspections and why they protect your business.',
          blocks: [
            { type: 'paragraph', content: 'Inspections are the evidence trail that protects you when a tenant disputes deposit deductions. Without documented inspections, you have no proof of the room\'s condition before or after a tenancy.' },
            { type: 'key_term', term: 'Pre-Inspection (Move-In)', content: 'Conducted before a tenant moves in. Documents the room\'s condition at the start of the tenancy. Sets the baseline.' },
            { type: 'key_term', term: 'Post-Inspection (Move-Out)', content: 'Conducted when a tenant moves out. Compares condition against the pre-inspection. Any new damage is documented and costed.' },
            { type: 'heading', content: 'When to Inspect' },
            { type: 'checklist', items: [
              'Pre-inspection: when a lease is created (or just before move-in)',
              'Post-inspection: during the lease termination process',
              'Ad-hoc: any time you suspect damage or want to check on a room',
            ]},
            { type: 'tip', content: 'Always conduct a post-inspection BEFORE processing the deposit payout. The inspection costs are automatically deducted from the deposit calculation.' },
          ],
        },
        {
          id: 'lesson-conduct-inspection',
          title: 'Conducting an Inspection',
          estimatedMinutes: 10,
          objective: 'Complete a full inspection checklist with photos and cost estimates.',
          blocks: [
            { type: 'paragraph', content: 'Inspections are done from either the **Leases** page or the **Lease Termination** form. The checklist covers 37 items across all areas of the room.' },
            { type: 'heading', content: 'Starting an Inspection from Leases' },
            { type: 'numbered_steps', items: [
              'Go to **Leases** and find the active lease.',
              'Click the **clipboard icon** (Inspect Room) next to the lease.',
              'Choose whether this is a **Pre-Inspection** or **Post-Inspection**.',
              'The inspection checklist opens.',
            ]},
            { type: 'heading', content: 'Completing the Checklist' },
            { type: 'numbered_steps', items: [
              'Work through each checklist category: Walls & Ceiling, Floors, Windows & Doors, Bathroom, Kitchen, Electrical, Furniture & Fixtures.',
              'For each item, select: **Good**, **Damaged**, or **Missing**.',
              'For any item marked Damaged or Missing, enter the **Repair Cost** in rands.',
              'Add notes for anything that needs explanation.',
              'Upload **Before Photos** (pre-inspection) or **After Photos** (post-inspection). Photos are stored securely and linked to the lease.',
              'Click **Save Inspection** when complete.',
            ]},
            { type: 'heading', content: 'How Inspection Costs Affect Deposit' },
            { type: 'paragraph', content: 'When you process a deposit payout after a post-inspection, the total repair costs from the inspection are automatically deducted from the deposit refund amount. The tenant receives: Deposit - Outstanding Rent - Inspection Repair Costs = Refund.' },
            { type: 'warning', content: 'Be specific and accurate when entering repair costs. Inflated or vague costs can be challenged by tenants. Always use market rates and keep receipts for actual repair work done.' },
          ],
        },
      ],
    },
    // ──────────────────────────────────────────────────────────────────────────
    {
      id: 'mod-reports-admin',
      title: 'Reports & Monitoring',
      description: 'Use reports to monitor income, occupancy, and overdue accounts.',
      icon: 'BarChart3',
      lessons: [
        {
          id: 'lesson-reports-overview',
          title: 'Using the Reports Page',
          estimatedMinutes: 8,
          objective: 'Read and act on all four report sections: income, occupancy, room status, and overdue accounts.',
          blocks: [
            { type: 'paragraph', content: 'The Reports page (available to System Admins only) gives you a financial and operational snapshot of your rental business. Navigate to it via **Reports** in the sidebar.' },
            { type: 'heading', content: 'Monthly Income Summary' },
            { type: 'paragraph', content: 'The top KPI row shows: **Collected** (total rent received this month), **Outstanding** (rent still unpaid), **Occupancy %** (occupied+locked rooms ÷ total rooms), and **Deposit Liability** (total deposits held across all tenants).' },
            { type: 'key_term', term: 'Deposit Liability', content: 'The total amount of deposits you hold on behalf of tenants. This is money you owe back — important for your accounting and for regulatory compliance.' },
            { type: 'heading', content: 'The 6-Month Bar Chart' },
            { type: 'paragraph', content: 'Shows collected (green) vs outstanding (red) rent for the last 6 months. Click any bar to switch the detail view to that month. Use this to spot trends — a growing red bar means collection is deteriorating.' },
            { type: 'heading', content: 'Overdue Accounts' },
            { type: 'paragraph', content: 'Lists every tenant with unpaid rent from any past month. Shows which months are overdue and the total amount owed. Export this list to CSV and use it for collection calls every Monday morning.' },
            { type: 'heading', content: 'Exporting Data' },
            { type: 'numbered_steps', items: [
              'Click **"Export Income"** to download a CSV of income by facility for the selected month.',
              'Click **"Export Overdue"** to download a CSV of all overdue accounts.',
              'Open in Excel or Google Sheets for reconciliation.',
            ]},
            { type: 'tip', content: 'Run the Reports page at the end of every month to close the books. Export the income CSV and file it with your accounting records.' },
          ],
        },
      ],
    },
  ],
};
